import hero from "@/assets/pool1.jpeg";
import garden from "@/assets/pool.jpeg";
import bedroom1 from "@/assets/bedroom1.jpeg";
import bedroom2 from "@assets/bedroom2.jpeg";
import living from "@/assets/livingroom.jpeg";
import outdoorRoom from "@/assets/chill.jpeg";"@assets/sunset.jpeg";
import kitchen from "@/assets/kichen.jpeg";
import bathroom from "@/assets/bathroom.jpeg";

export type Locale = "en" | "el";
export type Localized = { en: string; el: string };

export const siteConfig = {
  airbnbUrl: "[https://www.airbnb.gr/s/homes?c=.pi0.pk273496144_131023145409&sem_automaid=true&gad_source=1&gad_campaignid=273496144&gbraid=0AAAAADz55LlP9ZiGTuQFeB3P4KJD7tSf6&gclid=Cj0KCQjwt9jVBhDXARIsAFSP-6dZcfL50m1smVU2OISyJFfvyFr19GSVsyihYCVwHzYTIgnBnTYcerEaAsM_EALw_wcB&dynamic_product_ids%5B%5D=20017438&omni_page_id=27964",
  instagramUrl: "#",
  phone: "[6970052618]",
  registryNumber: "00002419157",
  mapUrl:
    "https://www.openstreetmap.org/export/embed.html?bbox=23.88%2C38.20%2C24.02%2C38.30&layer=mapnik&marker=38.2236%2C23.9236",
};

export const images = {
  hero: "/pool1.jpeg",
  garden: "/poοl.jpeg",
  bedroom1: "/bedroom1.jpeg",
  bedroom2: "/bedroom2.jpeg",
  kitchen: "/kichen.jpeg",
  bathroom: "/bathroom.jpeg",
  living: "/livingroom.jpeg",
  outdoorRoom: "/sunset.jpeg",
  gallery: [
    { src: hero, category: "Pool", alt: { en: "Private pool overlooking the Evian Gulf", el: "Η ιδιωτική πισίνα με θέα στον Ευβοϊκό" } },
    { src: garden, category: "Garden", alt: { en: "Shaded dining in the Mediterranean garden", el: "Σκιερή τραπεζαρία στον μεσογειακό κήπο" } },
    { src: bedroom1,category: "Interior", alt: { en: "Sunlit main bedroom", el: "Το φωτεινό κύριο υπνοδωμάτιο" } },
    { src: bedroom2,category: "Interior", alt: { en: "Second cozy bedroom", el: "Το δεύτερο άνετο υπνοδωμάτιο" } }, 
    { src: kitchen,category: "Interior", alt: { en: "Equipped kitchen", el: " Εξοπλισμένη κουζίνα" } },
    { src: bathroom,category: "Interior", alt: { en: "Clean bathroom", el: "Καθαρό μπάνιο" } },
    { src: living, category: "Interior", alt: { en: "Living room ", el: "Καθιστικό " } },
    { src: outdoorRoom, category: "Views", alt: { en: "Separate garden room at sunset", el: "Το ανεξάρτητο δωμάτιο στο ηλιοβασίλεμα" } },
   ],
};

export const copy = {
  en: {
    nav: ["Story", "Space", "Pool", "Gallery", "Location", "Reviews", "FAQ"],
    heroEyebrow: "Varnavas · Attica · Greece",
    heroTitle: "Your private hilltop escape, 30 km from Athens",
    heroText: "A quiet guesthouse with your own private pool, a sprawling garden, and sea views over the Evian Gulf.",
    availability: "Check availability",
    seeSpace: "See the space",
    badge: "Guest Favourite on Airbnb · top 10% of homes",
    whyTitle: "A stay that feels entirely your own",
    why: [
      ["Private pool", "Long, peaceful swims from morning until starlight."],
      ["Sea views", "A wide blue horizon across the Evian Gulf."],
      ["Hosts who care", "Warm local guidance, with your privacy always respected."],
    ],
    facts: ["Up to 6 guests", "2 bedrooms", "Private pool", "Sea view", "Pet-friendly", "Free parking", "Wi-Fi", "Air conditioning"],
    aboutKicker: "The story",
    aboutTitle: "A family retreat, cared for personally",
    aboutBody: "Giotas Country House was made for unhurried family days. It is especially comfortable for a family with up to three children, with room to play, a quiet setting and a large pool reserved entirely for you.",
    aboutBody2: "Tony (Antonis) and Giota live in the house above the guesthouse. They are close enough to help, share a favourite taverna or solve the smallest detail—yet thoughtful about giving every guest complete privacy.",
    hosts: "Tony & Giota",
    hostsNote: "Speaks Greek & English · Replies within an hour",
    spaceKicker: "Where you'll sleep",
    spaceTitle: "Simple, generous spaces for slow days",
    rooms: [
      ["Main bedroom", "Double bed · air conditioning · TV", "A restful room with a handmade modern chest of drawers and soft garden light."],
      ["Living room", "Double bed · double sofa bed · kitchen", "A flexible family space alongside a fully equipped kitchen."],
      ["Separate outdoor room", "Double bed", "An independent room opening directly to the quiet garden."],
    ],
    essentials: "Also included: 1 bathroom · 32-inch HDTV · fully equipped kitchen",
    poolKicker: "Pool & garden",
    poolTitle: "The blue heart of the house",
    poolBody: "The long lap-style pool is made for proper swims, lazy floating and family games. It is available seasonally, 24 hours a day. The garden and the whole area in front of the guesthouse are exclusively yours, with a foosball table and an open view to the sea.",
    safety: "The pool is not fenced or locked and there is a play/climbing structure on the property. Please supervise children at all times.",
    amenitiesKicker: "Everything you need",
    amenitiesTitle: "Thoughtful comforts, indoors and out",
    amenityGroups: [
      ["Outdoors", ["Private outdoor pool", "Garden view", "Bay & sea view", "Pool toys & games", "Play structure"]],
      ["Inside", ["Fully equipped kitchen", "Wi-Fi", "32-inch HDTV"]],
      ["Comfort", ["Air conditioning", "Pets allowed", "Free on-site parking"]],
      ["Safety", ["Outdoor security cameras on the property", "First aid essentials"]],
    ],
    showAll: "Show all amenities",
    showLess: "Show fewer",
    galleryKicker: "A closer look",
    galleryTitle: "Days in the sun, evenings in the garden",
    filters: ["All", "Pool", "Garden", "Interior", "Views"],
    locationKicker: "Location & around",
    locationTitle: "Between Athens and the Evian Gulf",
    locationBody: "The house rests on a peaceful Varnavas hilltop, looking across the water to Euboea. The exact address is shared after booking.",
    distances: [["Varnavas beach", "about 15 min by car"], ["Scenic hiking trails", "close to the house"], ["Athens", "about 30 km"]],
    localTip: "Our hosts happily recommend their favourite local restaurants and hidden spots.",
    reviewsKicker: "Guest reviews",
    reviewsTitle: "Loved for the little things",
    basedOn: "from 100 Airbnb reviews",
    categories: [["Cleanliness", "5.0"], ["Accuracy", "5.0"], ["Check-in", "5.0"], ["Communication", "5.0"], ["Location", "5.0"], ["Value", "4.9"]],
    mentions: "What guests mention most",
    mentionTags: ["Hospitality", "Pool", "Views", "Location", "Cleanliness", "Family"],
    testimonials: [
      ["Catherine", "Aug 2026", "Tony and Giota were incredibly friendly and recommended wonderful places and restaurants. The house was amazing, the pool was used daily, and the view was incredible. We created some truly magical memories."],
      ["Marc", "Aug 2026", "Exceptional hospitality from warm and attentive hosts. The house is decorated with great attention to detail, with a fantastic view and excellent pool."],
      ["Joanna", "Aug 2026", "Absolutely wonderful hosts from start to finish. Tony and Giota made us feel completely at home."],
      ["Styliani", "Aug 2025", "Everything was flawless. It’s no accident you can’t easily find a booking. The garden with the pool and foosball table were the highlight."],
      ["Myrto", "Sep 2024", "We hosted my daughter’s birthday and everyone left thrilled. Our hosts had thought of everything."],
    ],
    readReviews: "Read all 100 reviews on Airbnb",
    eventsKicker: "Small celebrations",
    eventsTitle: "Celebrate with us.",
    eventsBody: "Birthdays and intimate daytime gatherings can be arranged by agreement, with an additional charge for extra guests.",
    askEvent: "Ask about an event",
    bookingKicker: "Plan your stay",
    bookingTitle: "Your quiet escape starts here",
    checkIn: "Check-in",
    checkOut: "Check-out",
    guests: "Guests",
    bookAirbnb: "Book on Airbnb",
    enquiry: "Send a direct enquiry",
    name: "Name",
    email: "Email",
    phone: "Phone (optional)",
    message: "Tell us a little about your stay",
    send: "Send enquiry",
    sending: "Sending…",
    successTitle: "Thank you—we’ll be in touch soon.",
    successText: "Tony and Giota will reply personally, usually within an hour.",
    required: "Please complete the required fields and choose valid dates.",
    essentialsTitle: "House essentials",
    houseRules: ["Check-in 15:00–21:00", "Check-out before 12:00", "Maximum 6 guests", "Pets are welcome", "Free cancellation on many dates—see booking terms"],
    faqTitle: "Good to know",
    faqs: [
      ["How far is it from Athens?", "The house is about 30 km from Athens. Journey time varies with traffic."],
      ["Is the pool private?", "Yes. The pool, garden and the area in front of the guesthouse are exclusively for your group."],
      ["Is it suitable for young children?", "Families are very welcome. The pool is not fenced or locked, so children need active supervision at all times."],
      ["Are pets allowed?", "Yes, pets are welcome. Please mention them when you enquire."],
      ["Can we host a small event?", "Small daytime celebrations can be arranged in advance for an additional guest fee."],
      ["What time is check-in and check-out?", "Check-in is from 15:00 to 21:00. Check-out is before 12:00."],
      ["Is parking available?", "Yes, free parking is available on the property."],
      ["How do I book?", "Check dates and book through Airbnb, or send Tony and Giota a direct enquiry."],
    ],
    footerTag: "Quiet days, open skies, and a welcome that feels personal.",
    listed: "Listed on Airbnb",
    registration: "Registration number (Greek short-term rental registry)",
  },
  el: {
    nav: ["Η ιστορία", "Το σπίτι", "Πισίνα", "Φωτογραφίες", "Τοποθεσία", "Κριτικές", "Συχνές ερωτήσεις"],
    heroEyebrow: "Βαρνάβας · Αττική · Ελλάδα",
    heroTitle: "Το δικό σας καταφύγιο στον λόφο, μόλις 30 χλμ. από την Αθήνα",
    heroText: "Ένας ήσυχος ξενώνας με ιδιωτική πισίνα, μεγάλο κήπο και ανοιχτή θέα στον Ευβοϊκό.",
    availability: "Έλεγχος διαθεσιμότητας",
    seeSpace: "Δείτε το σπίτι",
    badge: "Αγαπημένο των επισκεπτών στο Airbnb · στο κορυφαίο 10% των καταλυμάτων",
    whyTitle: "Μια διαμονή που νιώθετε πραγματικά δική σας",
    why: [["Ιδιωτική πισίνα", "Μεγάλες, ήρεμες βουτιές από το πρωί ως το βράδυ."], ["Θέα στη θάλασσα", "Ο γαλάζιος ορίζοντας του Ευβοϊκού μπροστά σας."], ["Οικοδεσπότες που νοιάζονται", "Ζεστή φιλοξενία και τοπικές προτάσεις, με απόλυτο σεβασμό στην ιδιωτικότητά σας."]],
    facts: ["Έως 6 επισκέπτες", "2 υπνοδωμάτια", "Ιδιωτική πισίνα", "Θέα στη θάλασσα", "Κατοικίδια δεκτά", "Δωρεάν πάρκινγκ", "Wi-Fi", "Κλιματισμός"],
    aboutKicker: "Η ιστορία μας", aboutTitle: "Ένα οικογενειακό καταφύγιο με προσωπική φροντίδα",
    aboutBody: "Το Εξοχικό σπίτι Giotas δημιουργήθηκε για ανέμελες οικογενειακές μέρες. Είναι ιδανικό για οικογένεια με έως τρία παιδιά, με άπλετο χώρο για παιχνίδι, ησυχία και μια μεγάλη πισίνα αποκλειστικά για εσάς.",
    aboutBody2: "Ο Τόνι (Αντώνης) και η Γιώτα μένουν στο σπίτι πάνω από τον ξενώνα. Είναι κοντά όταν τους χρειαστείτε—για μια καλή ταβέρνα ή την παραμικρή βοήθεια—και ταυτόχρονα σέβονται απόλυτα την ιδιωτικότητά σας.",
    hosts: "Τόνι & Γιώτα", hostsNote: "Μιλούν Ελληνικά & Αγγλικά · Απαντούν άμεσα",
    spaceKicker: "Πού θα κοιμηθείτε", spaceTitle: "Απλοί, άνετοι χώροι για ξέγνοιαστες μέρες",
    rooms: [["Κύριο υπνοδωμάτιο", "Διπλό κρεβάτι · κλιματισμός · TV", "Ένα ήρεμο δωμάτιο με χειροποίητη μοντέρνα συρταριέρα και απαλό φως από τον κήπο."], ["Καθιστικό", "Διπλό κρεβάτι · διπλός καναπές-κρεβάτι · κουζίνα", "Ένας ευέλικτος οικογενειακός χώρος δίπλα στην πλήρως εξοπλισμένη κουζίνα."], ["Ανεξάρτητο εξωτερικό δωμάτιο", "Διπλό κρεβάτι", "Ένα ξεχωριστό δωμάτιο που ανοίγει απευθείας στον ήσυχο κήπο."]],
    essentials: "Επίσης: 1 μπάνιο · HDTV 32 ιντσών · πλήρως εξοπλισμένη κουζίνα",
    poolKicker: "Πισίνα & κήπος", poolTitle: "Η γαλάζια καρδιά του σπιτιού",
    poolBody: "Η μακριά πισίνα είναι ιδανική για κολύμπι, χαλάρωση και οικογενειακά παιχνίδια. Λειτουργεί εποχικά και είναι διαθέσιμη όλο το 24ωρο. Ο κήπος και ο χώρος μπροστά από τον ξενώνα είναι αποκλειστικά δικοί σας, με ποδοσφαιράκι και ανεμπόδιστη θέα στη θάλασσα.",
    safety: "Η πισίνα δεν είναι περιφραγμένη ούτε κλειδώνει και στο κτήμα υπάρχει κατασκευή παιχνιδιού/αναρρίχησης. Παρακαλούμε επιβλέπετε πάντα τα παιδιά.",
    amenitiesKicker: "Όλα όσα χρειάζεστε", amenitiesTitle: "Φροντισμένες ανέσεις μέσα και έξω",
    amenityGroups: [["Εξωτερικοί χώροι", ["Ιδιωτική εξωτερική πισίνα", "Θέα στον κήπο", "Θέα στον κόλπο & τη θάλασσα", "Παιχνίδια πισίνας", "Κατασκευή παιχνιδιού"]], ["Στο σπίτι", ["Πλήρως εξοπλισμένη κουζίνα", "Wi-Fi", "HDTV 32 ιντσών"]], ["Άνεση", ["Κλιματισμός", "Κατοικίδια δεκτά", "Δωρεάν πάρκινγκ"]], ["Ασφάλεια", ["Εξωτερικές κάμερες ασφαλείας στο κτήμα", "Είδη πρώτων βοηθειών"]]],
    showAll: "Όλες οι παροχές", showLess: "Λιγότερα",
    galleryKicker: "Μια πιο κοντινή ματιά", galleryTitle: "Μέρες στον ήλιο, βράδια στον κήπο", filters: ["Όλα", "Πισίνα", "Κήπος", "Εσωτερικό", "Θέα"],
    locationKicker: "Τοποθεσία & γύρω περιοχή", locationTitle: "Ανάμεσα στην Αθήνα και τον Ευβοϊκό", locationBody: "Το σπίτι βρίσκεται σε έναν ήσυχο λόφο του Βαρνάβα, με θέα προς την Εύβοια. Η ακριβής διεύθυνση κοινοποιείται μετά την κράτηση.",
    distances: [["Παραλία Βαρνάβα", "περίπου 15' με το αυτοκίνητο"], ["Όμορφα μονοπάτια πεζοπορίας", "κοντά στο σπίτι"], ["Αθήνα", "περίπου 30 χλμ."]], localTip: "Οι οικοδεσπότες μας θα χαρούν να σας προτείνουν αγαπημένα εστιατόρια και κρυφές γωνιές της περιοχής.",
    reviewsKicker: "Κριτικές επισκεπτών", reviewsTitle: "Ξεχωρίζει στις μικρές λεπτομέρειες", basedOn: "από 100 κριτικές στο Airbnb",
    categories: [["Καθαριότητα", "5.0"], ["Ακρίβεια", "5.0"], ["Άφιξη", "5.0"], ["Επικοινωνία", "5.0"], ["Τοποθεσία", "5.0"], ["Αξία", "4.9"]], mentions: "Όσα αναφέρουν πιο συχνά οι επισκέπτες", mentionTags: ["Φιλοξενία", "Πισίνα", "Θέα", "Τοποθεσία", "Καθαριότητα", "Οικογένεια"],
    testimonials: [["Catherine", "Αύγ 2026", "Ο Τόνι και η Γιώτα ήταν απίστευτα φιλικοί και μας πρότειναν υπέροχα μέρη και εστιατόρια. Το σπίτι ήταν καταπληκτικό, η πισίνα έγινε καθημερινή συνήθεια και η θέα ήταν μοναδική. Δημιουργήσαμε πραγματικά μαγικές αναμνήσεις."], ["Marc", "Αύγ 2026", "Εξαιρετική φιλοξενία από ζεστούς και προσεκτικούς οικοδεσπότες. Το σπίτι είναι διακοσμημένο με πολλή φροντίδα, με φανταστική θέα και εξαιρετική πισίνα."], ["Joanna", "Αύγ 2026", "Υπέροχοι οικοδεσπότες από την αρχή μέχρι το τέλος. Ο Τόνι και η Γιώτα μάς έκαναν να νιώσουμε σαν στο σπίτι μας."], ["Styliani", "Αύγ 2025", "Όλα ήταν άψογα. Δεν είναι τυχαίο που δύσκολα βρίσκεις διαθέσιμη κράτηση. Ο κήπος με την πισίνα και το ποδοσφαιράκι ήταν το καλύτερο σημείο."], ["Myrto", "Σεπ 2024", "Κάναμε τα γενέθλια της κόρης μου και όλοι έφυγαν ενθουσιασμένοι. Οι οικοδεσπότες είχαν σκεφτεί τα πάντα."]],
    readReviews: "Διαβάστε και τις 100 κριτικές στο Airbnb",
    eventsKicker: "Μικρές γιορτές", eventsTitle: "Γιορτάστε μαζί μας.", eventsBody: "Γενέθλια και μικρές ημερήσιες συγκεντρώσεις μπορούν να οργανωθούν κατόπιν συνεννόησης, με επιπλέον χρέωση για τους πρόσθετους καλεσμένους.", askEvent: "Ρωτήστε για εκδήλωση",
    bookingKicker: "Οργανώστε τη διαμονή σας", bookingTitle: "Η ήρεμη απόδρασή σας ξεκινά εδώ", checkIn: "Άφιξη", checkOut: "Αναχώρηση", guests: "Επισκέπτες", bookAirbnb: "Κράτηση στο Airbnb", enquiry: "Στείλτε απευθείας αίτημα", name: "Όνομα", email: "Email", phone: "Τηλέφωνο (προαιρετικό)", message: "Πείτε μας λίγα λόγια για τη διαμονή σας", send: "Αποστολή αιτήματος", sending: "Αποστολή…", successTitle: "Ευχαριστούμε—θα επικοινωνήσουμε σύντομα.", successText: "Ο Τόνι και η Γιώτα θα σας απαντήσουν προσωπικά, συνήθως μέσα σε μία ώρα.", required: "Συμπληρώστε τα απαραίτητα πεδία και επιλέξτε έγκυρες ημερομηνίες.", essentialsTitle: "Βασικές πληροφορίες", houseRules: ["Άφιξη 15:00–21:00", "Αναχώρηση πριν τις 12:00", "Έως 6 επισκέπτες", "Τα κατοικίδια είναι ευπρόσδεκτα", "Δωρεάν ακύρωση σε πολλές ημερομηνίες—δείτε τους όρους κράτησης"],
    faqTitle: "Χρήσιμες πληροφορίες", faqs: [["Πόσο απέχει από την Αθήνα;", "Το σπίτι απέχει περίπου 30 χλμ. από την Αθήνα. Ο χρόνος διαδρομής εξαρτάται από την κίνηση."], ["Είναι ιδιωτική η πισίνα;", "Ναι. Η πισίνα, ο κήπος και ο χώρος μπροστά από τον ξενώνα είναι αποκλειστικά για την παρέα σας."], ["Είναι κατάλληλο για μικρά παιδιά;", "Οι οικογένειες είναι ευπρόσδεκτες. Η πισίνα δεν είναι περιφραγμένη ούτε κλειδώνει, επομένως τα παιδιά χρειάζονται συνεχή επίβλεψη."], ["Επιτρέπονται κατοικίδια;", "Ναι, τα κατοικίδια είναι ευπρόσδεκτα. Αναφέρετέ τα στο αίτημά σας."], ["Μπορούμε να κάνουμε μια μικρή εκδήλωση;", "Μικρές ημερήσιες γιορτές μπορούν να οργανωθούν εκ των προτέρων με επιπλέον χρέωση επισκεπτών."], ["Ποιες είναι οι ώρες άφιξης και αναχώρησης;", "Η άφιξη γίνεται 15:00–21:00 και η αναχώρηση πριν τις 12:00."], ["Υπάρχει πάρκινγκ;", "Ναι, υπάρχει δωρεάν πάρκινγκ στο κτήμα."], ["Πώς κάνω κράτηση;", "Ελέγξτε τις ημερομηνίες και κλείστε μέσω Airbnb ή στείλτε απευθείας αίτημα στον Τόνι και τη Γιώτα."]],
    footerTag: "Ήσυχες μέρες, ανοιχτός ορίζοντας και μια φιλοξενία πραγματικά προσωπική.", listed: "Στο Airbnb", registration: "Αριθμός Μητρώου Ακινήτου",
  },
} as const;
